### ISSUE TITLE
AssertionError: expected 4D input (got 3D input)

### ISSUE THREAD

**Issue by sgs66** [TorchDSP/torchsig#122]
Describe the bug
I'm running the example code in: 02_example_sig53_classifier.py, I encountered the following problem:

Environment Info
Python 3.9

Stacktra

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
File "/mnt/HDD1/sgs/torchsig-main/examples/02_example_sig53_classifier.py", line 230, in <module> 
    trainer.fit(example_model) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit 
    call._call_and_handle_interrupt( 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt 
    return trainer_fn(*args, **kwargs) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl 
    self._run(model, ckpt_path=ckpt_path) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run 
    results = self._run_stage() 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 976, in _run_stage 
    self._run_sanity_check() 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1005, in _run_sanity_check 
    val_loop.run() 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/loops/utilities.py", line 177, in _decorator 
    return loop_run(self, *args, **kwargs) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run 
    self._evaluation_step(batch, batch_idx, dataloader_idx) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 375, in _evaluation_step 
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values()) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 288, in _call_strategy_hook 
    output = fn(*args, **kwargs) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 378, in validation_step 
    return self.model.validation_step(*args, **kwargs) 
  File "/mnt/HDD1/sgs/torchsig-main/examples/02_example_sig53_classifier.py", line 194, in validation_step 
    loss = F.cross_entropy(self(x.float()), y) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl 
    return forward_call(*input, **kwargs) 
  File "/mnt/HDD1/sgs/torchsig-main/examples/02_example_sig53_classifier.py", line 168, in forward 
    return self.mdl(x.float()) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl 
    return forward_call(*input, **kwargs) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/timm/models/efficientnet.py", line 557, in forward 
    x = self.forward_features(x) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/timm/models/efficientnet.py", line 541, in forward_features 
    x = self.bn1(x) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl 
    return forward_call(*input, **kwargs) 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/timm/models/layers/norm_act.py", line 67, in forward 
    _assert(x.ndim == 4, f'expected 4D input (got {x.ndim}D input)') 
  File "/home/sgs/.conda/envs/yolov5test/lib/python3.9/site-packages/torch/__init__.py", line 833, in _assert 
    assert condition, message 
AssertionError: expected 4D input (got 3D input)

**Comment by gvanhoy** [comment]
Cannot reproduce from 0.3.1 :(. 

What does ```pip show``` output?

I believe the model instantiated in the example script (efficientnet) should be expecting a 3D input. The project requirements call for ```timm==0.5.4```, a different version of that may cause this error.
