### ISSUE TITLE
Error in generating the wideband sig53

### ISSUE THREAD

**Issue by paul-ang** [TorchDSP/torchsig#143]
Command ran:
`python scripts/generate_wideband_sig53.py --root=torchsig/data --all=True` 

Environment:
`MacOS, python3.9, torchsig==0.4.0`

The error occurred after 24% (5927/25000) of files has been generated.
 
Error message:
```
Traceback (most recent call last):
  File "/Users/guest/repo/torchsig/scripts/generate_wideband_sig53.py", line 70, in <module>
    main()
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/guest/repo/torchsig/scripts/generate_wideband_sig53.py", line 59, in main
    generate(root, configs)
  File "/Users/guest/repo/torchsig/scripts/generate_wideband_sig53.py", line 33, in generate
    creator.create()
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torchsig/utils/writer.py", line 157, in create
    for batch in tqdm.tqdm(self.loader, total=len(self.loader)):
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torchsig/datasets/wideband.py", line 1296, in __getitem__
    signal_iq_data, signal_description = signal_sources[source_idx][0]
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torchsig/datasets/wideband.py", line 631, in __getitem__
    iq_samples += burst.generate_iq()
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torchsig/datasets/wideband.py", line 341, in generate_iq
    iq_samples = modulated_burst[0][0]
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torchsig/datasets/synthetic.py", line 208, in __getitem__
    data=self._generate_samples(self.index[index]).tobytes(),
  File "/Users/guest/miniconda3/envs/torchsig/lib/python3.9/site-packages/torchsig/datasets/synthetic.py", line 696, in _generate_samples
    start_idx = np.random.randint(lower, upper)
  File "mtrand.pyx", line 765, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1247, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
```

**Comment by paul-ang** [comment]
Same error, but this time it happen much earlier at around 2%.

**Comment by gvanhoy** [comment]
Hm -- I'm going to comment out the code most likely causing this issue -- it seems like a simple adjustment in the randomization bounds, but it's hard to trace it.

**Comment by maker-slim** [comment]
I encountered the same problem as the landlord, how to solve this problem by the author, I see you closed it

**Comment by maker-slim** [comment]
I modified this：self.env = lmdb.Environment(path, subdir=True, map_size=int(1e12), max_dbs=2)，I modified to2e12，Then downloaded close to 200GB, which is only 47%, this dataset should not use so much memory, please the author to solve, thank you
