### ISSUE TITLE
Syntax error in generate_sig53.py: module 'os' has no attribute 'root'

### ISSUE THREAD

**Issue by MattCarrickPL** [TorchDSP/torchsig#145]
Running v0.4.0 tag and I get the following error when trying to generate the narrowband dataset:

$ python3 scripts/generate_sig53.py --root=torchsig/data --all=True

Traceback (most recent call last):
  File "scripts/generate_sig53.py", line 64, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in call
    return self.main(args, kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(args, **kwargs)
  File "scripts/generate_sig53.py", line 43, in main
    if not os.root.isdir(root):
AttributeError: module 'os' has no attribute 'root'

**Comment by MattCarrickPL** [comment]
Fixed in branch https://github.com/TorchDSP/torchsig/tree/145-syntax-error-in-generate_sig53py-module-os-has-no-attribute-root

**Comment by gvanhoy** [comment]
Done in #147
