### ISSUE TITLE
TypeError: cannot pickle 'module' object

### ISSUE THREAD

**Issue by garricklw** [TorchDSP/torchsig#71]
**Describe the bug**
I'm running the example code in: 00_example_sig53_dataset.py, but the call to creator.create() gives me a TypeError: cannot pickle 'module' object from the multiprocessing module, full stack trace below.

Also the two lines in the docs that use torch.data.DataLoader for using sig53 don't work, but that's another issue I suppose.

**Environment Info**
MacBook, OSX: 13.2.1 (22D68)
Python 3.10.10 virtualenv

**Stacktrace**

```
Traceback (most recent call last):
  File "/Users/garrickw/Documents/mudsum/perc-rf/venv/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/garrickw/Documents/mudsum/perc-rf/extern/torchsig/torchsig/utils/writer.py", line 57, in __iter__
    return iter(self.loader)
  File "/Users/garrickw/Documents/mudsum/perc-rf/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "/Users/garrickw/Documents/mudsum/perc-rf/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/garrickw/Documents/mudsum/perc-rf/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1043, in __init__
    w.start()
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'module' object
```

**Comment by gvanhoy** [comment]
Hm, I suspect this would be fixed if the "fork" context was used, which it's not by default on macOS and Windows.

In utils/writer.py
```python
        self.loader = DataLoader(
            dataset,
            shuffle=True,
            batch_size=batch_size,
            num_workers=num_workers,
            prefetch_factor=2,
            worker_init_fn=partial(DatasetLoader.worker_init_fn, seed=seed),
            multiprocessing_context=torch.multiprocessing.get_context("fork"), # add this line?
        )
```
