### ISSUE TITLE
Build Warning - AttributeError: module 'numpy' has no attribute 'typing'

### ISSUE THREAD

**Issue by sognefej** [TorchDSP/torchsig#9]
Warning while building torchsig: 

```
WARNING: autodoc: failed to import class 'datasets.Sig53' from module 'torchsig'; the following exception was raised:
Traceback (most recent call last):
  File "/home/sognefeste/Documents/TOOLS/torchsig/.torchsigenv/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 58, in import_module
    return importlib.import_module(modname)
  File "/home/sognefeste/.pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sognefeste/Documents/TOOLS/torchsig/torchsig/__init__.py", line 1, in <module>
    from torchsig import transforms
  File "/home/sognefeste/Documents/TOOLS/torchsig/torchsig/transforms/__init__.py", line 2, in <module>
    from . import system_impairment
  File "/home/sognefeste/Documents/TOOLS/torchsig/torchsig/transforms/system_impairment/__init__.py", line 1, in <module>
    from .si import *
  File "/home/sognefeste/Documents/TOOLS/torchsig/torchsig/transforms/system_impairment/si.py", line 9, in <module>
    from torchsig.transforms.functional import NumericParameter, IntParameter, FloatParameter
  File "/home/sognefeste/Documents/TOOLS/torchsig/torchsig/transforms/functional.py", line 10, in <module>
    class RandomStatePartial(Protocol):
  File "/home/sognefeste/Documents/TOOLS/torchsig/torchsig/transforms/functional.py", line 21, in RandomStatePartial
    def __call__(self, size: Union[int, Sequence[int]] = ...) -> np.typing.ArrayLike:
  File "/home/sognefeste/Documents/TOOLS/torchsig/.torchsigenv/lib/python3.8/site-packages/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typing'
```

Causes my program to crash importing the following: 
```python
from torchsig.datasets import Sig53, SignalDataset
```

Environment: 
```
python --version
Python 3.8.12
```

```
pip freeze
absl-py==1.2.0
aiohttp==3.8.3
aiosignal==1.2.0
alabaster==0.7.12
asttokens==2.0.8
async-timeout==4.0.2
attrs==22.1.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
better-apidoc==0.3.2
cachetools==5.2.0
certifi==2022.9.24
charset-normalizer==2.1.1
colorama==0.4.5
commonmark==0.9.1
contourpy==1.0.5
cycler==0.11.0
decorator==5.1.1
docutils==0.17.1
executing==1.1.0
filelock==3.8.0
fonttools==4.37.3
frozenlist==1.3.1
fsspec==2022.8.2
gdown==4.5.1
google-auth==2.12.0
google-auth-oauthlib==0.4.6
grpcio==1.49.1
h5py==3.7.0
icecream==2.1.3
idna==3.4
imagesize==1.4.1
importlib-metadata==4.12.0
ipdb==0.13.9
ipython==8.5.0
jedi==0.18.1
Jinja2==3.1.2
joblib==1.2.0
kiwisolver==1.4.4
llvmlite==0.39.1
lmdb==1.3.0
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.0
matplotlib-inline==0.1.6
multidict==6.0.2
numba==0.56.2
numpy==1.23.3
oauthlib==3.2.1
packaging==21.3
pandas==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
prompt-toolkit==3.0.31
protobuf==3.19.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyDeprecate==0.3.2
Pygments==2.13.0
pyparsing==3.0.9
PySocks==1.7.1
python-dateutil==2.8.2
pytorch-lightning==1.7.7
pytz==2022.2.1
PyWavelets==1.4.1
PyYAML==6.0
recommonmark==0.7.1
requests==2.28.1
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.1.2
scipy==1.9.1
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
sphinx==5.2.2
sphinx-rtd-theme==1.0.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.5.1
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
timm==0.5.4
toml==0.10.2
torch==1.12.1
torchmetrics==0.9.3
torchsig @ file:///home/sognefeste/Documents/TOOLS/torchsig
torchvision==0.13.1
tqdm==4.64.1
traitlets==5.4.0
typing-extensions==4.3.0
urllib3==1.26.12
wcwidth==0.2.5
Werkzeug==2.2.2
yarl==1.8.1
zipp==3.8.1
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by TorchDSP** [comment]
@sognefej’s PR resolves this issue. Closing. Thanks!
